### ISSUE TITLE
How do I setup @storybook/addon-styling-webpack with PostCSS

### ISSUE THREAD

**Issue by demarchenac** [storybookjs/addon-styling-webpack#1]
I was reading the docs for the [Styling addon](https://storybook.js.org/addons/@storybook/addon-styling), and I got it working with `PostCSS` as the [docs suggested](https://github.com/storybookjs/addon-styling/blob/main/docs/api.md#optionspostcss). 

Then, I noticed it was deprecated and that I should start using this addon instead. I want to know if the configuration to specificy that I'm using `PostCSS` should be similar to the `@storybook/addon-styling` config or not.

**Comment by Integrayshaun** [comment]
Hey @demarchenac 👋 

The API for addon-styling-webpack is fairly different to addon-styling but I do have a helper to get you started :)

Can you install `@storybook/addon-styling` then try running `npx @storybook/auto-config styling`?

This should get you set up but if you have any problems I can get you get things patched up :)

**Comment by spiess-demos** [comment]
Same case here, suggested fix works for me.

**Comment by spiess-demos** [comment]
> That's great to hear @spiess-demos 👍 How was the CLI experience for you?

i have to admit i rushed through it a little bit, but did not hit any hard obstacles.

**Comment by Integrayshaun** [comment]
No worries 😁 Couldn't have been horrible if you breezed through it

**Comment by demarchenac** [comment]
Hey good to know, thanks if I get any error I'll re-open or reference this issue again. 

Thanks!

**Comment by dpavloff** [comment]
Hey @integrayshaun! I'm trying to migrate from storybook `@storybook/addon-postcss` to `@storybook/addon-styling-webpack` and I'm having difficulties running the codegen `npx @storybook/auto-config styling`. 

For some reason the CLI exits without any logs after running it :(

What can be the reason for that? 

`storybook: 7.6.17`

<img width="731" alt="Screenshot 2024-04-03 at 17 28 59" src="https://github.com/storybookjs/addon-styling-webpack/assets/23011754/3746e993-9970-4b3e-83c6-ed19d2a374a3">

**Comment by FranRom** [comment]
I have the same issue even after running `npx @storybook/auto-config styling`
Before I had:
` {
      name: '@storybook/addon-styling',
      options: {
        postCss: true
      }
    }`

and it works even after the migration but If I try to make it work with: 
`    {
      name: '@storybook/addon-styling-webpack',

      options: {
        rules: [
          {
            test: /\.css$/,
            sideEffects: true,
            use: [
              require.resolve('style-loader'),
              {
                loader: require.resolve('css-loader'),
                options: {
                  importLoaders: 1
                }
              },
              {
                loader: require.resolve('postcss-loader'),
                options: {
                  implementation: require.resolve('postcss')
                }
              }
            ]
          }
        ]
      }
    }`
The css modules are not loaded. 
I try all the configs in the addon doc without luck...
