### ISSUE TITLE
[Bug] Angular workspace - Unable to find storybook main.js config

### ISSUE THREAD

**Issue by leogouveia** [storybookjs/addon-styling-webpack#10]
### Steps to reproduce the behavior

1. Go to storybook project
2. Execute `npx storybook add @storybook/addon-styling-webpack`
3. See error

### Expected behavior

Should install addon-styling-webpack and works as expected.

### Screenshots and/or logs

```
❯ npx storybook add @storybook/addon-styling-webpack
Unable to find storybook main.js config
```

### Environment

 - OS: MacOs Sonoma 14.0
 - Node.js version: v18.16.1
 - NPM version: 9.5.1

### Additional context

When I try to add the lib in a Angular Workspace, it cannot find storybook project.

It seems that the feature has not yet been implemented and there is no alternative to use it (such as manually configuring it).

**Comment by Integrayshaun** [comment]
Hey @leogouveia, the add command needs to be run in the parent directory of the projects `.storybook` directory.

However, `@storybook/addon-styling-webpack` is not compatible with Angular as storybook uses Angular's complex webpack setup to aovid breaking anything.

What tooling are you trying to configure with your Angular storybook? I can give you some help from there

**Comment by leogouveia** [comment]
It seems that your package is the least of the problems when using angular libraries. I can’t make storybook run or build properly on both ng cli and nx. 
It would be cool if the library documented what the add command does so we could manually configure it.

**Comment by Integrayshaun** [comment]
@leogouveia I can certainly add some documentation around what the command does so that you could configure the addon manually.

However, this addon will not help you solve your problem as it would override Angular's WebPack config.

Can you tell me more about your setup so that I can help you configure Storybook for your stack?
