### ISSUE TITLE
Storybook 8 support?

### ISSUE THREAD

**Issue by muhghazaliakbar** [storybookjs/addon-styling-webpack#19]
### Describe the bug

I just upgraded to storybook 8 and this warning appear
<img width="1217" alt="Screenshot 2024-03-13 at 16 35 05" src="https://github.com/storybookjs/addon-styling-webpack/assets/8321936/e5aa7211-a764-4021-9257-0262f0a49003">

### Steps to reproduce the behavior

Just setup a new project with `Storybook 8` and install this library. 

### Expected behavior

Just want to make sure if this library is already support `Storybook 8` yet or not.

### Screenshots and/or logs

```
WARN The following packages are incompatible with Storybook 8.0.0 as they depend on different major versions of Storybook packages:
WARN - @storybook/addon-styling-webpack@0.0.6
```

### Environment

```
Storybook Environment Info:

  System:
    OS: macOS 14.4
    CPU: (8) arm64 Apple M1
    Shell: 3.6.1 - /opt/homebrew/bin/fish
  Binaries:
    Node: 19.3.0 - ~/.nvm/versions/node/v19.3.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.2.0 - ~/.nvm/versions/node/v19.3.0/bin/npm
    pnpm: 8.6.1 - /opt/homebrew/bin/pnpm <----- active
  Browsers:
    Chrome: 122.0.6261.112
    Safari: 17.4
  npmPackages:
    @storybook/addon-docs: ^8.0.0 => 8.0.0
    @storybook/addon-essentials: ^8.0.0 => 8.0.0
    @storybook/addon-links: ^8.0.0 => 8.0.0
    @storybook/addon-styling-webpack: ^0.0.6 => 0.0.6
    @storybook/manager-api: ^8.0.0 => 8.0.0
    @storybook/nextjs: ^8.0.0 => 8.0.0
    @storybook/react: ^8.0.0 => 8.0.0
    @storybook/storybook-deployer: ^2.8.16 => 2.8.16
    @storybook/theming: ^8.0.0 => 8.0.0
    storybook: ^8.0.0 => 8.0.0
    storybook-addon-apollo-client: ^5.0.0 => 5.0.0
```

**Comment by shilman** [comment]
released!

**Comment by spiess-demos** [comment]
Maybe it is a good idea to reflect this in the README, as well? When migrating from SB7 to SB8 (with a pre-v1 release of addon-styling-webpack), i came to the assumotion that addon-styling-webpack does not support SB8, based on the sentence in the README:

> Get started in Storybook 7 faster with popular styling tools.
