### ISSUE TITLE
[Bug] `npx storybook@latest add @storybook/addon-styling-webpack` throw and error

### ISSUE THREAD

**Issue by javierlopezdeancos** [storybookjs/addon-styling-webpack#4]
### Steps to reproduce the behavior

1. Go to your storybook project
2. Execute `npx storybook@latest add @storybook/addon-styling-webpack`

### Expected behavior

Should install addon-styling-webpack and works as expected.

### Screenshots and/or logs

```
Need to install the following packages:
  storybook@7.4.0
Ok to proceed? (y) y
Verifying @storybook/addon-styling-webpack
Installing @storybook/addon-styling-webpack@^0.0.3
Adding '@storybook/addon-styling-webpack' to main.js addons field.
Running postinstall script for @storybook/addon-styling-webpack
Error running postinstall script for @storybook/addon-styling-webpack
TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received undefined
at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at normalizeSpawnArguments (node:child_process:545:3)
    at Object.spawn (node:child_process:750:13)
    at t (/Users/javierlopezdeancos/Code/AtomicJar/tcc-web/node_modules/@storybook/addon-styling-webpack/bin/postinstall.js:5:130)
    at postinstallAddon (/Users/javierlopezdeancos/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@storybook/cli/dist/generate.js:172:834)
    at add (/Users/javierlopezdeancos/.npm/_npx/bc7e1e37fcb46ffc/node_modules/@storybook/cli/dist/generate.js:172:2421) {
  code: 'ERR_INVALID_ARG_TYPE'
}
```

### Environment

 - OS: MacOs Ventura 13.4.1
 - Node.js version: v18.16.0
 - NPM version: v9.5.1

**Comment by Integrayshaun** [comment]
Hey @javierlopezdeancos 👋 

I'm just trying to hunt down that issue for that now!

In the mean time, please run this command instead:

`npx @storybook/auto-config styling`

**Comment by javierlopezdeancos** [comment]
Hey @Integrayshaun thanks for the fast feedback 

with `npx @storybook/auto-config styling` the result in terminal looks well 
<img width="1671" alt="Captura de pantalla 2023-09-01 a las 11 59 00" src="https://github.com/storybookjs/addon-styling-webpack/assets/1202463/d230e240-ed6c-457f-819b-5cd436b8f394">
<img width="895" alt="Captura de pantalla 2023-09-01 a las 12 00 19" src="https://github.com/storybookjs/addon-styling-webpack/assets/1202463/81f03726-8bc3-4e12-8914-209835fbb2e8">

But the css modules imported in my next app looks that continues not imported in the storybook app 😕
